main/urls.py
from django.urls import path

from .views import index, other_page, BBLoginView, profile, BBLogoutView, \
    ChangeUserInfoView, BBPasswordChangeView, RegisterUserView, \
    RegisterDoneView, user_activate, DeleteUserView, BBPasswordResetView, \
    BBPasswordResetDoneView, BBPasswordResetConfirmView, \
    BBPasswordResetCompleteView, profile_bb_detail, \
    profile_bb_add, profile_bb_change, profile_bb_delete, generate_password, export_to_excel, import_from_excel, \
    by_category, add_category, search

app_name = 'main'
urlpatterns = [
    path('accounts/register/activate/<str:sign>/', user_activate, name='register_activate'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(),name='register'),
    path('accounts/logout/', BBLogoutView.as_view(), name='logout'),
    path('accounts/password/change/', BBPasswordChangeView.as_view(), name='password_change'),
    path('accounts/profile/delete/', DeleteUserView.as_view(), name='profile_delete'),
    path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/profile/change/<int:pk>/', profile_bb_change, name='profile_bb_change'),
    path('accounts/profile/delete/<int:pk>/', profile_bb_delete, name='profile_bb_delete'),
    path('accounts/profile/add/', profile_bb_add, name='profile_bb_add'),
    path('accounts/profile/<int:pk>/', profile_bb_detail, name='profile_bb_detail'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/password/reset/done/', BBPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/password/reset/', BBPasswordResetView.as_view(), name='password_reset'),
    path('accounts/password/confirm/complete/', BBPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('accounts/password/confirm/<uidb64>/<token>/', BBPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/login/', BBLoginView.as_view(), name='login'),
    path('generate_password/', generate_password, name='generate_password'),
    path('export/', export_to_excel, name='export_to_excel'),
    path('import/', import_from_excel, name='import_from_excel'),
    path('by_category/<int:pk>/', by_category, name='by_category'),
    path('add_category/', add_category, name='add_category'),
    path('search/', search, name='search'),
    path('<str:page>/', other_page, name='other'),
    path('', index, name='index'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError

from .models import AdvUser, Bb, BbCategory
from .apps import user_registered


class ChangeUserInfoForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'first_name', 'last_name')


class RegisterUserForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')
    password1 = forms.CharField(
        label='Пароль', widget=forms.PasswordInput, help_text=password_validation.password_validators_help_text_html())
    password2 = forms.CharField(
        label='Пароль (повторно)', widget=forms.PasswordInput, help_text='Введите тот же самый пароль еще раз для проверки')

    def clean_password1(self):
        password1 = self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password1)
        return password1

    def clean(self):
        super(RegisterUserForm, self).clean()
        # super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError(
              'Введенные пароли не совпадают', code='password_mismatch')}
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = False
        user.is_activated = False
        if commit:
            user.save()
        user_registered.send(RegisterUserForm, instance=user)
        return user

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'password1', 'password2',
                  'first_name', 'last_name')


class SearchForm(forms.Form):
    name = forms.CharField(required=False, max_length=100, label='Поиск')


class BbForm(forms.ModelForm):
    class Meta:
        model = Bb
        fields = '__all__'
        widgets = {'author': forms.HiddenInput}


class GeneratePasswordForm(forms.Form):
    num_chars = forms.IntegerField()


class ImportFromExcelForm(forms.Form):
    file = forms.FileField()


class BbCategoryForm(forms.ModelForm):
    class Meta:
        model = BbCategory
        fields = ['name', 'author']
        widgets = {'author': forms.HiddenInput}

main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from django.contrib.auth.views import LoginView, LogoutView, \
    PasswordChangeView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import UpdateView, CreateView, \
    DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from django.core.signing import BadSignature
from django.contrib.auth import logout
from django.contrib import messages
from django.conf import settings
from openpyxl import load_workbook

from cryptography.fernet import Fernet
import base64
import random
import tablib

from .models import AdvUser, Bb, BbCategory
from .forms import ChangeUserInfoForm, RegisterUserForm, GeneratePasswordForm, BbForm, ImportFromExcelForm, \
    BbCategoryForm, SearchForm
from .utilities import signer, import_data_from_excel


def index(request):
    bbs = Bb.objects.filter(is_active=True)
    context = {'bbs': bbs}
    return render(request, 'main/index.html', context)


def other_page(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        return render(request, 'main/404.html')
    return HttpResponse(template.render(request=request))


class BBLoginView(LoginView):
    template_name = 'main/login.html'


@login_required
def profile(request):
    bbs = Bb.objects.filter(author=request.user.pk)
    categories = BbCategory.objects.filter(author=request.user)
    for bb in bbs:
        pas = base64.urlsafe_b64decode(bb.password)
        cipher_pass = Fernet(settings.ENCRYPT_KEY)
        decod_pass = cipher_pass.decrypt(pas).decode("ascii")
        bb.password = decod_pass
    search_form = SearchForm()
    context = {'bbs': bbs, 'categories': categories, 'search_form': search_form}
    return render(request, 'main/profile.html', context)


@login_required
def add_category(request):
    if request.method == 'POST':
        form = BbCategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('main:profile')
    else:
        form = BbCategoryForm(initial={'author': request.user.pk})
    context = {'form': form}
    return render(request, 'main/profile_category_add.html', context)


@login_required
def by_category(request, pk):
    bbs = Bb.objects.filter(author=request.user, category__id=pk)
    for bb in bbs:
        pas = base64.urlsafe_b64decode(bb.password)
        cipher_pass = Fernet(settings.ENCRYPT_KEY)
        decod_pass = cipher_pass.decrypt(pas).decode("ascii")
        bb.password = decod_pass
    categories = BbCategory.objects.filter(author=request.user)
    context = {'bbs': bbs, 'categories': categories}
    return render(request, 'main/by_category.html', context)


@login_required
def search(request):
    form = SearchForm(request.POST)
    search_form = SearchForm()
    if form.is_valid():
        keyword = form.cleaned_data['name']
        bbs = Bb.objects.filter(author=request.user, title=keyword)
        for bb in bbs:
            pas = base64.urlsafe_b64decode(bb.password)
            cipher_pass = Fernet(settings.ENCRYPT_KEY)
            decod_pass = cipher_pass.decrypt(pas).decode("ascii")
            bb.password = decod_pass
        context = {'bbs': bbs, 'search_form': search_form}
        return render(request, 'main/profile.html', context)


class BBLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'main/logout.html'


class ChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin,
                                              UpdateView):
    model = AdvUser
    template_name = 'main/change_user_info.html'
    form_class = ChangeUserInfoForm
    success_url = reverse_lazy('main:profile')
    success_message = 'Данные пользователя изменены'

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


class BBPasswordChangeView(SuccessMessageMixin, LoginRequiredMixin,
                                                PasswordChangeView):
    template_name = 'main/password_change.html'
    success_url = reverse_lazy('main:profile')
    success_message = 'Пароль пользователя изменен'


class RegisterUserView(CreateView):
    model = AdvUser
    template_name = 'main/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('main:register_done')


class RegisterDoneView(TemplateView):
    template_name = 'main/register_done.html'


def user_activate(request, sign):
    try:
        username = signer.unsign(sign)
    except BadSignature:
        return render(request, 'main/bad_signature.html')
    user = get_object_or_404(AdvUser, username=username)
    if user.is_activated:
        template = 'main/user_is_activated.html'
    else:
        template = 'main/activation_done.html'
        user.is_active = True
        user.is_activated = True
        user.save()
    return render(request, template)


class DeleteUserView(LoginRequiredMixin, DeleteView):
    model = AdvUser
    template_name = 'main/delete_user.html'
    success_url = reverse_lazy('main:index')

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        logout(request)
        messages.add_message(request, messages.SUCCESS, 'Пользователь удален')
        return super().post(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


class BBPasswordResetView(PasswordResetView):
    template_name = 'main/password_reset.html'
    subject_template_name = 'email/reset_letter_subject.txt'
    email_template_name = 'email/reset_letter_body.txt'
    success_url = reverse_lazy('main:password_reset_done')


class BBPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'main/password_reset_done.html'


class BBPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'main/password_confirm.html'
    success_url = reverse_lazy('main:password_reset_complete')


class BBPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'main/password_complete.html'


@login_required
def profile_bb_detail(request, pk):
    bb = get_object_or_404(Bb, pk=pk)
    pas = base64.urlsafe_b64decode(bb.password)
    cipher_pass = Fernet(settings.ENCRYPT_KEY)
    decod_pass = cipher_pass.decrypt(pas).decode("ascii")
    bb.password = decod_pass
    context = {'bb': bb}
    return render(request, 'main/profile_bb_detail.html', context)


@login_required
def profile_bb_add(request):
    if request.method == 'POST':
        form = BbForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS,
                                     'Запись добавлена')
            return redirect('main:profile')
    else:
        form = BbForm(initial={'author': request.user.pk})
    context = {'form': form}
    return render(request, 'main/profile_bb_add.html', context)


@login_required
def profile_bb_change(request, pk):
    bb = get_object_or_404(Bb, pk=pk)
    pas = base64.urlsafe_b64decode(bb.password)
    cipher_pass = Fernet(settings.ENCRYPT_KEY)
    decod_pass = cipher_pass.decrypt(pas).decode("ascii")
    bb.password = decod_pass
    if request.method == 'POST':
        form = BbForm(request.POST, request.FILES, instance=bb)
        if form.is_valid():
            bb = form.save()
            messages.add_message(request, messages.SUCCESS, 'Запись исправлена')
            return redirect('main:profile')
    else:
        form = BbForm(instance=bb)
    context = {'form': form}
    return render(request, 'main/profile_bb_change.html', context)


@login_required
def profile_bb_delete(request, pk):
    bb = get_object_or_404(Bb, pk=pk)
    if request.method == 'POST':
        bb.delete()
        messages.add_message(request, messages.SUCCESS, 'Объявление удалено')
        return redirect('main:profile')
    else:
        context = {'bb': bb}
        return render(request, 'main/profile_bb_delete.html', context)


def generate_password(request):
    chars = '+-/*!&$#?=@<>abcdefghijklnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890'
    if request.method == 'POST':
        form = GeneratePasswordForm(request.POST)
        if form.is_valid():
            password = ''
            for i in range(int(form.data.get('num_chars'))):
                password += random.choice(chars)
            messages.add_message(request, messages.SUCCESS,
                                 f'Пароль: {password}')
            return redirect('main:generate_password')
    else:
        form = GeneratePasswordForm()
    context = {'form': form}
    return render(request, 'main/generate_password.html', context)


class XlsxExport(object):

    FIELDS = {
        'title': 'title',
        'service_name': 'service_name',
        'login': 'login',
        'password': 'password',
    }

    def __init__(self, user):

main/templates/main/bad_signature.html
{% extends "layout/basic.html" %}

{% block title %}Ошибка при активации{% endblock %}

{% block content %}
<h2>Активация</h2>
<p>Активация пользователя с таким именем прошла неудачно.</p>
<p><a href="{% url 'main:register' %}">Зарегистрироваться повторно</a></p>
{% endblock %}

main/templates/main/by_category.html
{% extends "layout/basic.html" %}

{% load thumbnail %}
{% load static %}

{% block title %}Профиль пользователя{% endblock %}

{% block categories %}
<p class="nav-link root">Категории</p>
{% for category in categories %}
<a class="nav-link root" href="{% url 'main:by_category' pk=category.pk %}">{{category.name}}</a>
{%endfor%}
<a class="nav-link root" href="{% url 'main:add_category' %}">Добавить категорию</a>
{% endblock %}

{% block content %}
<h2>Профиль пользователя {{ user.username }}</h2>
{% if user.first_name and user.last_name %}
<p>Здравствуйте, {{ user.first_name }} {{ user.last_name }}!</p>
{% else %}
<p>Здравствуйте!</p>
{% endif %}
<p><a href="{% url 'main:profile_bb_add' %}">Добавить пароль</a></p>
<p><a href="{% url 'main:generate_password' %}">Сгенерировать пароль</a></p>
<p><a href="{% url 'main:import_from_excel' %}">Импорт паролей</a></p>
<p><a href="{% url 'main:export_to_excel' %}">Экспорт паролей</a></p>
{% if bbs %}
<h3>Ваши пароли</h3>
<ul class="list-unstyled">
    {% for bb in bbs %}
    <li class="media my-5 p-3 border">
        {% url 'main:profile_bb_detail' pk=bb.pk as url %}
        <a href="{{ url }}{{ all }}"></a>
        <div class="media-body">
          <h3><a href="{{ url }}{{ all }}"> {{ bb.title }}</a></h3>
            <p>Link: <a href={{ bb.service_name }}>{{ bb.title }}</a></p>
          <p>Login: {{ bb.login }}</p>
            <p>Password: {{ bb.password }}</p>
          <p class="text-right font-italic">{{ bb.created_at }}</p>
          <p class="text-right mt-2">
            <a href="{% url 'main:profile_bb_change' pk=bb.pk %}">Исправить</a>
            <a href="{% url 'main:profile_bb_delete' pk=bb.pk %}">Удалить</a>
            <button class="btn btn-sm btn-primary" onclick="copyToClipboard('{{bb.password}}')">Скопировать</button>
          </p>
        </div>
    </li>
    {% endfor %}
</ul>
{% endif %}

<script>
    function copyToClipboard(text) {
   navigator.clipboard.writeText(text);
}
</script>

{% endblock %}

main/templates/main/change_user_info.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Правка личных данных{% endblock %}

{% block content %}
<h2>Правка личных данных пользователя {{ user.username }}</h2>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Сохранить' %}{% endbuttons %}
</form>
{% endblock %}

main/templates/main/delete_user.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Удаление пользователя{% endblock %}

{% block content %}
<h2>Удаление пользователя {{ object.username }}</h2>
<form method="post">
    {% csrf_token %}
    {% buttons submit='Удалить' %}{% endbuttons %}
</form>
{% endblock %}

main/templates/main/import_from_excel.html
{% extends "layout/basic.html" %}
{% load bootstrap4 %}
{% block title %}Импорт паролей{% endblock %}

{% block content %}
<h2>Импорт паролей</h2>
<form method="post" enctype="multipart/form-data" action="{% url 'main:import_from_excel' %}">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Импорт' %}{% endbuttons %}
</form>
{% endblock %}

main/templates/main/index.html
{% extends "layout/basic.html" %}

{% load thumbnail %}
{% load static %}

{% block content %}
<p><a href="{% url 'main:generate_password' %}">Сгенерировать пароль</a></p>
{% endblock %}

main/templates/main/logout.html
{% extends "layout/basic.html" %}

{% block title %}Выход{% endblock %}

{% block content %}
<h2>Выход</h2>
<p>Вы успешно вышли с сайта.</p>
{% endblock %}

main/templates/main/password_complete.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Сброс пароля завершен{% endblock %}

{% block content %}
<h2>Сброс пароля завершен</h2>
<p>Для пользователя установлен новый пароль.</p>
<p><a href="{% url 'main:login' %}">Вход на сайт</a></p>
{% endblock %}

main/templates/main/password_confirm.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Ввод нового пароля{% endblock %}

{% block content %}
<h2>Ввод нового пароля пользователя</h2>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Сохранить' %}{% endbuttons %}
</form>
{% endblock %}

main/templates/main/profile.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}
{% load static %}

{% block title %}Профиль пользователя{% endblock %}

{% block categories %}
<p class="nav-link root">Категории</p>
{% for category in categories %}
<a class="nav-link root" href="{% url 'main:by_category' pk=category.pk %}">{{category.name}}</a>
{%endfor%}
<a class="nav-link root" href="{% url 'main:add_category' %}">Добавить категорию</a>
{% endblock %}

{% block content %}
<h2>Профиль пользователя {{ user.username }}</h2>
{% if user.first_name and user.last_name %}
<p>Здравствуйте, {{ user.first_name }} {{ user.last_name }}!</p>
{% else %}
<p>Здравствуйте!</p>
{% endif %}
<form method="post" enctype="multipart/form-data" action="{% url 'main:search' %}">
    {% csrf_token %}
    {% bootstrap_form search_form layout='horizontal' size='small' %}
    {% buttons submit='Поиск' %}{% endbuttons %}
</form>
<p><a href="{% url 'main:profile_bb_add' %}">Добавить пароль</a></p>
<p><a href="{% url 'main:generate_password' %}">Сгенерировать пароль</a></p>
<p><a href="{% url 'main:import_from_excel' %}">Импорт паролей</a></p>
<p><a href="{% url 'main:export_to_excel' %}">Экспорт паролей</a></p>
{% if bbs %}
<h3>Ваши пароли</h3>
<ul class="list-unstyled">
    {% for bb in bbs %}
    <li class="media my-5 p-3 border">
        {% url 'main:profile_bb_detail' pk=bb.pk as url %}
        <a href="{{ url }}{{ all }}"></a>
        <div class="media-body">
          <h3><a href="{{ url }}{{ all }}"> {{ bb.title }}</a></h3>
            <p>Link: <a href={{ bb.service_name }}>{{ bb.title }}</a></p>
          <p>Login: {{ bb.login }}</p>
            <p>Password: {{ bb.password }}</p>
          <p class="text-right font-italic">{{ bb.created_at }}</p>
          <p class="text-right mt-2">
            <a href="{% url 'main:profile_bb_change' pk=bb.pk %}">Исправить</a>
            <a href="{% url 'main:profile_bb_delete' pk=bb.pk %}">Удалить</a>
            <button class="btn btn-sm btn-primary" onclick="copyToClipboard('{{bb.password}}')">Скопировать</button>
          </p>
        </div>
    </li>
    {% endfor %}
</ul>
{% endif %}

<script>
    function copyToClipboard(text) {
   navigator.clipboard.writeText(text);
}
</script>

{% endblock %}

main/templates/main/profile_bb_delete.html
{% extends "layout/basic.html" %}

{% block title %}Удаление объявления - Профиль пользователя{% endblock %}

{% block content %}
<h2>Удаление объявления</h2>
<div class="container-fluid mt-3">
    <div class="row">
        {% if bb.image %}
        <div class="col-md-auto"><img src="{{ bb.image.url }}" class="main-image"></div>
        {% endif %}
        <div class="col">
            <h2>{{ bb.title }}</h2>
            <p>{{ bb.content }}</p>
            <p class="font-weight-bold">{{ bb.price }} руб.</p>
            <p>{{ bb.contacts }}</p>
            <p class="text-right font-italic">Добавлено {{ bb.created_at }}</p>
        </div>
    </div>
</div>
<form method="post">
    {% csrf_token %}
    <input type="submit" value="Удалить">
</form>
{% endblock %}

main/templates/main/profile_category_add.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}
{% block title %}Добавление категории - Профиль пользователя{% endblock %}

{% block content %}
<h2>Добавление категории</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Добавить' %}{% endbuttons %}
</form>
{% endblock %}

main/templates/main/register_done.html
{% extends "layout/basic.html" %}

{% block title %}Регистрация завершена{% endblock %}

{% block content %}
<h2>Регистрация</h2>
<p>Регистрация пользователя завершена.</p>
<p>На адрес электронной почты, указанный пользователем, выслано письмо для
активации.</p>
{% endblock %}

main/templates/main/register_user.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Регистрация{% endblock %}

{% block content %}
<h2>Регистрация нового пользователя</h2>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Зарегистрироваться' %}{% endbuttons %}
</form>
{% endblock %}